apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sw-factory-agent-data
  namespace: sw-factory
  labels:
    app: sw-factory-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: # cluster default
